"""rename department

Revision ID: 1d82d2393600
Revises: 4bcb8b3ab046
Create Date: 2025-04-06 08:55:23.251511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d82d2393600'
down_revision = '4bcb8b3ab046'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
