"""rename address

Revision ID: b865767d82c9
Revises: 1d82d2393600
Create Date: 2025-04-06 09:00:39.059332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b865767d82c9'
down_revision = '1d82d2393600'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'address', new_column_name= 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'location', new_column_name= 'address')
    # ### end Alembic commands ###
